### PR TITLE
Only stash changes when needed

### PR DESCRIPTION
**Pull request by Chronial**

### CODE REVIEW

**Comment by Chronial** [comment]
Not too sure on the architecture here.

**Comment by msiemens** [comment]
@Chronial Could you rebase unto the latest master? Python 3.7 testing was broken and thus this PR doesn't pass the CI run.

**Comment by Chronial** [comment]
@msiemens done

**Comment by msiemens** [comment]
Thanks for contributing, it's very much apperciated 🙂

**Pull request merged**
