### PR TITLE
Upgrade click to ^8.0

### PR DESCRIPTION
**Pull request by hugovk**
Click 8.0.x is now out:

* https://click.palletsprojects.com/en/8.0.x/changes/

### CODE REVIEW

**Comment by msiemens** [comment]
Thanks for the PR, @hugovk! Had you had a chance to test if there are no breaking changes that break PyGitUp? If everything's fine, I'll be glad to merge this 🙁

**Comment by hugovk** [comment]
You're welcome! Yep, I've got `click==8.0.1` locally and `git up` has been working fine.

**Comment by msiemens** [comment]
Great, thanks for your time and effort! I'll publish a new version of PyGitUp right now 🙂

**Comment by hugovk** [comment]
And thank you for maintaining PyGitUp!

**Comment by msiemens** [comment]
Just a quick note that PyGitUp v2.0.3 has been pushed 🚢

**Pull request merged**
