### PR TITLE
Update README for quick dev setup and code cleanup

### PR DESCRIPTION
**Pull request by liijunwei**
Add guide for eaiser dev setup

### CODE REVIEW

**Comment by msiemens** [comment]
Thanks for the suggestion, @liijunwei!

I think having a quick guide to setting up a dev environment in the README is a great idea! But while I have seen Golang projects use a Makefile for setting up a dev environment, I don't know of any other Python projects that do this. In my view, having a guide in the README would be enough. What do you think?

**Comment by liijunwei** [comment]
yes, I agree, one of them is good enough 👍

**Comment by liijunwei** [comment]
let me remove the Makefile

**Comment by liijunwei** [comment]
pls feel free to edit this pr 🙏

**Comment by hugovk** [comment]
> But while I have seen Golang projects use a Makefile for setting up a dev environment, I don't know of any other Python projects that do this.

Makefiles are fairly common in Python projects, especially for Sphinx docs. Here's a few in projects I have checked out:

- https://github.com/python/cpython
- https://github.com/python/cpython/tree/main/Doc
- https://github.com/python/devguide/
- https://github.com/python-pillow/Pillow
- https://github.com/python-pillow/Pillow/tree/main/docs
- https://github.com/python-pillow/docker-images
- https://github.com/jazzband/tablib/tree/master/docs
- https://github.com/sphinx-doc/sphinx
- https://github.com/hugovk/osmviz/tree/main/html
- https://github.com/certifi/python-certifi

But it really depends on the needs of the maintainers/developers, if they don't often use the Makefiles, they'll go out of date and stop working. They need maintaining too.

**Comment by msiemens** [comment]
> https://github.com/python/cpython

Well, that's a C project, where using Makefiles is a common convention. Regarding the `docs/` directories: the Makefiles in these directories only build the documentation but don't set up a dev environment. But you're right, some projects like python-certifi you listed do use Makefiles for dev environment setup.



> let me remove the Makefile

Thanks, I'll merge your pull request! 🙂

**Pull request merged**
