### PR TITLE
Added auto-push support

### PR DESCRIPTION
**Pull request by WoLpH**
Additionally allows to push tags and all branches as well

### CODE REVIEW

**Comment by WoLpH** [comment]
This fixes #71

**Comment by msiemens** [comment]
Thanks 🙃 I'll try to release a new version of TinyDB with these changes soon (next week or the one following)

**Comment by msiemens** [comment]
This is released in v1.5.0 now 🙂

**Comment by WoLpH** [comment]
Awesome, thanks!

**Pull request merged**
