### PR TITLE
Add Python 3 support

### PR DESCRIPTION
**Pull request by r4ts0n**
Use the excellent `six` library to support both Python 2 and 3.
All tests passes on my machine for Python 3.4.3 and 2.7.9

### CODE REVIEW

**Comment by msiemens** [comment]
Wow, great work @r4ts0n! I think we could even release PyGitUp 2.0 after merging this.

One minor thing: Could also update the *Python 3 compatibility* paragraph in the readme? (And have you any idea why the Travis tests didn't run? It's not a problem, I'm just wondering)

**Comment by r4ts0n** [comment]
Updated README to reflect the Python 3 support.
(Not sure why Travis did not run, but it builds now)

**Comment by msiemens** [comment]
Thank you, @r4ts0n! I'm currently on vacation and thus will propably release PyGitUp v2.0.0 next week :)

**Comment by msiemens** [comment]
Quick note: I decided to take a more conservative approach in regards to versioning and release this change as v1.3.0. This is also closer to semantic versioning as there haven't been any breaking changes.

**Pull request merged**
